spring:
  datasource:
    url: jdbc:mysql://meetbti-database.cp4eeaas28gc.ap-northeast-2.rds.amazonaws.com:13306/meetbti?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: meetbti0829
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
